version: 0.2

env:
  parameter-store:
    API_KEY: /${CODE_PIPELINE_NAME}/API_KEY

phases:
  install:
    commands:
      - npm install
      - cd lambdas/login && npm ci && cd ../..

  build:
    commands:
      - test -n "$API_KEY" && echo "API_KEY is set"
      - npm run build

      - cd lambdas/login
      - zip -r login.zip index.js package.json node_modules
      - "aws lambda update-function-code --function-name login --zip-file fileb://login.zip --region eu-central-1"
      - cd ../..

artifacts:
  base-directory: build
  files:
    - "**/*"
